[package]
name = "git-issue"
version = "0.1.0"
authors = ["hexium310 <hexium310@gmail.com>"]

[dependencies]
clap = { version = "2.29.3", features = ["yaml"] }
reqwest = "0.8.4"
regex = "0.2.5"
serde_json = "1.0.9"
